#load zgen
source ~/.dotfiles/shell/zgen/zgen.zsh

#check if there's no init script
if ! zgen saved; then
    echo 'creating a zgen save'

    zgen oh-my-zsh

    #plugins
    zgen oh-my-zsh plugins/git
    zgen load zsh-users/zsh-syntax-highlighting
    zgen load tarruda/zsh-autosuggestions

    #save all to init script
    zgen save
fi

#load shortcuts
source ~/.dotfiles/shell/shortcuts

#load aliases
source ~/.dotfiles/shell/aliases

#load theme
source ~/.dotfiles/shell/desu.zsh-theme