#load antigen
source $HOME/.dotfiles/shell/antigen/antigen.zsh

#load various lib files
antigen bundle robbyrussell/oh-my-zsh lib/

#load other plugins
antigen bundle git
antigen bundle unixorn/autoupdate-antigen.zshplugin
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle tarruda/zsh-autosuggestions

#load theme
antigen theme $HOME/.dotfiles/shell/theme/ db