#load antigen
source $HOME/.dotfiles/shell/antigen/antigen.zsh

#load theme
antigen theme dboleslawski/dotfiles/shell/theme/

#load plugins
antigen bundle unixorn/autoupdate-antigen.zshplugin
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle tarruda/zsh-autosuggestions